'use client';

import * as React from 'react';
import { PageHeader } from '@/components/page-header';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Download, FileText, FileBarChart2, Presentation, Clock, CheckCircle2 } from 'lucide-react';
import { useBusinessStore } from '@/store/business-store';

export default function ReportsPage() {
  const currentBusiness = useBusinessStore((state) => state.currentBusiness);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Custom Reports"
        description="Generate formatted PDFs, presentations, and Excel dumps for committees."
      />

      <div className="grid gap-4 md:gap-6 md:grid-cols-3">
        <Card className="hover:border-primary/50 transition-colors cursor-pointer group">
          <CardHeader>
            <div className="h-12 w-12 bg-primary/10 text-primary rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <FileBarChart2 className="h-6 w-6" />
            </div>
            <CardTitle>Credit Appraisal Memo</CardTitle>
            <CardDescription>Comprehensive 10-page deep dive with all financial ratios and bureau scores.</CardDescription>
          </CardHeader>
          <CardContent>
            <Button className="w-full" variant="outline">
              <Download className="mr-2 h-4 w-4" /> Generate PDF
            </Button>
          </CardContent>
        </Card>

        <Card className="hover:border-primary/50 transition-colors cursor-pointer group">
          <CardHeader>
            <div className="h-12 w-12 bg-emerald-500/10 text-emerald-500 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <FileText className="h-6 w-6" />
            </div>
            <CardTitle>CMA Data Export</CardTitle>
            <CardDescription>Excel-formatted Credit Monitoring Arrangement data for bank upload.</CardDescription>
          </CardHeader>
          <CardContent>
            <Button className="w-full" variant="outline">
              <Download className="mr-2 h-4 w-4" /> Export XLSX
            </Button>
          </CardContent>
        </Card>

        <Card className="hover:border-primary/50 transition-colors cursor-pointer group">
          <CardHeader>
            <div className="h-12 w-12 bg-amber-500/10 text-amber-500 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <Presentation className="h-6 w-6" />
            </div>
            <CardTitle>Committee Pitch Deck</CardTitle>
            <CardDescription>Auto-generated presentation highlighting business strengths.</CardDescription>
          </CardHeader>
          <CardContent>
            <Button className="w-full" variant="outline">
              <Download className="mr-2 h-4 w-4" /> Export PPTX
            </Button>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Clock className="h-5 w-5 text-primary" />
            Recent Generations
          </CardTitle>
          <CardDescription>Historical report generation logs for {currentBusiness.name}</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-muted/50 text-muted-foreground uppercase text-xs">
                <tr>
                  <th className="px-4 py-3 font-medium">Report Type</th>
                  <th className="px-4 py-3 font-medium">Generated By</th>
                  <th className="px-4 py-3 font-medium">Date</th>
                  <th className="px-4 py-3 font-medium">Status</th>
                  <th className="px-4 py-3 font-medium">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                <tr className="bg-card hover:bg-muted/20">
                  <td className="px-4 py-3 font-medium flex items-center gap-2"><FileBarChart2 className="h-4 w-4 text-primary" /> Credit Appraisal Memo</td>
                  <td className="px-4 py-3">System Auto-Gen</td>
                  <td className="px-4 py-3 text-muted-foreground">Today, 10:45 AM</td>
                  <td className="px-4 py-3"><Badge variant="outline" className="bg-emerald-500/10 text-emerald-500 border-emerald-500/20"><CheckCircle2 className="h-3 w-3 mr-1" /> Ready</Badge></td>
                  <td className="px-4 py-3"><Button variant="ghost" size="sm" className="h-8">Download</Button></td>
                </tr>
                <tr className="bg-card hover:bg-muted/20">
                  <td className="px-4 py-3 font-medium flex items-center gap-2"><FileText className="h-4 w-4 text-emerald-500" /> CMA Data Export</td>
                  <td className="px-4 py-3">Credit Analyst</td>
                  <td className="px-4 py-3 text-muted-foreground">Yesterday, 02:15 PM</td>
                  <td className="px-4 py-3"><Badge variant="outline" className="bg-emerald-500/10 text-emerald-500 border-emerald-500/20"><CheckCircle2 className="h-3 w-3 mr-1" /> Ready</Badge></td>
                  <td className="px-4 py-3"><Button variant="ghost" size="sm" className="h-8">Download</Button></td>
                </tr>
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
