'use client';

import * as React from 'react';
import { PageHeader } from '@/components/page-header';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { useChat } from 'ai/react';
import { useBusinessStore } from '@/store/business-store';
import { intelligenceData as healthData } from '@/data/intelligence-data';
import { creditData, insightsData } from '@/data/credit-insights-data';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Loader2, Sparkles } from 'lucide-react';

interface AIInsightPageProps {
  title: string;
  description: string;
  prompt: string;
  icon?: React.ReactNode;
}

export function AIInsightPage({ title, description, prompt, icon = <Sparkles className="h-5 w-5 text-primary" /> }: AIInsightPageProps) {
  const currentBusiness = useBusinessStore((state) => state.currentBusiness);

  const currentContext = React.useMemo(() => ({
    currentBusiness,
    financialData: healthData[currentBusiness.id] || healthData['default'],
    creditInsightsData: {
      credit: creditData[currentBusiness.id] || creditData['default'],
      insights: insightsData[currentBusiness.id] || insightsData['default']
    }
  }), [currentBusiness]);

  const { messages, append, isLoading } = useChat({
    api: '/api/chat',
    body: { data: currentContext },
    initialMessages: []
  });

  // Auto-trigger the overview generation on load
  React.useEffect(() => {
    if (messages.length === 0) {
      append({
        id: '1',
        role: 'user',
        content: prompt
      });
    }
  }, [currentBusiness, prompt, append, messages.length]);

  const aiMessage = messages.findLast(m => m.role === 'assistant');

  return (
    <div className="space-y-6">
      <PageHeader
        title={title}
        description={description}
      />

      <Card className="border-primary/20 bg-primary/5 min-h-[400px]">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            {icon}
            AI Generated Insight
          </CardTitle>
          <CardDescription>Generated by NEXUS AI in real-time based on live data.</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading && !aiMessage && (
            <div className="flex flex-col items-center justify-center py-20 text-muted-foreground">
              <Loader2 className="h-8 w-8 animate-spin mb-4 text-primary" />
              <p>Analyzing datasets...</p>
            </div>
          )}

          {aiMessage && (
            <div className="prose prose-sm dark:prose-invert max-w-none">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{aiMessage.content}</ReactMarkdown>
            </div>
          )}

          {isLoading && aiMessage && (
             <div className="flex items-center gap-2 mt-4 text-xs text-muted-foreground">
               <Loader2 className="h-3 w-3 animate-spin text-primary" /> AI is generating...
             </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
